name: Wands
main: com.i0dev.lightningWand.Heart
version: 1
author: i01
description: wands
website: https://i0dev.com/
commands:
  wand:
    description: Main Wand Cmd
    usage: /wand give <type> [player]
permissions:
  wands.give:
    description: Give a wand
    default: op
  wands.reoad:
    description: Reload config
    default: op