name: ${project.build.finalName}
main: com.i0dev.Wands.Heart
version: 1
author: i01
description: Configurable, customizable, lightning wands.
website: ${project.url}
softdepend:
  - Factions
  - PlaceHolderAPI
commands:
  wand:
    description: Main Wand Cmd
    usage: /wand give <type> [player]
permissions:
  wands.give:
    description: Give a wand
    default: op
  wands.reoad:
    description: Reload config
    default: op